language: python

install:
        - pip install -r requirements.txt

jobs:
        include:
                - stage: test code
                  python: "3.5"
                  script: ls
                - stage: deploy code
                  python: "3.5"
                  script: echo date
