language: python
python:
        - "3.5"

sudo: true

install:
        pip install -r requirements.txt

before_script:
        - ls
script:

        - lspytest
        - ls
        - sudo apt install pip

after_success:
        ls
