stages:
        - test
        - deploy

dist: "trusty"
language: python

python: "3.6"

before_install:
        skip

install:
        - pip install -r requirements.txt

script: skip

jobs:
        include:
                - stage: test
                  script: pytest -x --ff
                - stage: test
                  script: flake8 pois
                - stage: deploy
                  #install: skip
                  script: isort -rc -sl .
                  script: black .
                  after_success: echo 'finito'

