language: python
python:
        - "3.5"

sudo: true
stages:
        - test
        - deploy

unittests:
        stage: test
        install:
                - pip install -r requirements.txt
        script:
                - pytest

deploylast:
        stage: deploy
        script:
                - sudo apt install pip
                - ls
