language: python

install:
        - pip install -r requirements.txt

jobs:
        include:
                - stage: test code
                  python: "3.5"
                  script: ls
                - stage: more
                  script: cat requirements.txt
                - stage: deploy code
                  python: "3.5"
                  install: python -v
                  script: echo date
                  after_success: echo 'redondo'
