language: python
python:
        - "3.5"
virtualenv:
        system_site_packages: true

sudo: true

install:
        pip install -r requirements.txt
script:
        - lspytest
        - ls
        - sudo apt install pip
